name: Build and Test

on:
  - pull_request
  - push

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.08.x
          - 4.09.x
          - 4.10.x
          - 4.11.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: actions-ml/setup-ocaml@master
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
          dune-cache: ${{ matrix.os != 'windows-latest' }}

      - run: |
          rm /Users/runner/.opam/opam-init/hooks/sandbox.sh
          curl -sLo /Users/runner/.opam/opam-init/hooks/sandbox.sh https://raw.githubusercontent.com/ocaml/opam/master/src/state/shellscripts/sandbox_exec.sh
          chmod 777 /Users/runner/.opam/opam-init/hooks/sandbox.sh
        if: matrix.os == 'macos-latest'

      - run: |
          opam pin add dune.dev https://github.com/dra27/dune.git#progress-4167
          opam depext dune --install

      - name: Install nasm
        uses: ilammy/setup-nasm@v1

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build -p eqaf
